Align REST endpoints for consistency
hmcts/opal-fines-service pull request #195
Opened 2024-02-13 09:20 UTC by RustyHMCTS

`/api/defendant-account/` endpoint has now changed to `/api/defendantAccount/`

In addition, the `/api/defendantAccount/details` endpoint has been changed to `/api/defendantAccount/xxxxxx`, where xxxxxx is the defendant account id.

**Does this PR introduce a breaking change?** (check one with "x")

```
[*] Yes
[ ] No
```

2024-02-13 09:31 UTC, DeclanClarkeCGI approved these changes

2024-02-13 12:59 UTC, sabahirfan commented on src/main/java/uk/gov/hmcts/opal/controllers/AccountTransferController.java
> +@RequestMapping("/api/accountTransfer")
[Use lowercase separate words with hyphens for Path Segments [129]](https://hmcts.github.io/restful-api-standards/#129)

2024-02-13 12:59 UTC, sabahirfan commented
[Use lowercase separate words with hyphens for Path Segments [129]](https://hmcts.github.io/restful-api-standards/#129)

2024-02-13 13:13 UTC, sabahirfan commented on src/main/java/uk/gov/hmcts/opal/controllers/DebtorDetailController.java
> +@RequestMapping("/api/debtorDetail")
```suggestion
@RequestMapping("/api/debtor-detail")
```
[Use lowercase separate words with hyphens for Path Segments [129]](https://hmcts.github.io/restful-api-standards/#129)

2024-02-13 14:56 UTC, sabahirfan requested changes
[Use lowercase separate words with hyphens for Path Segments [129]](https://hmcts.github.io/restful-api-standards/#129)

2024-02-15 08:56 UTC, sabahirfan approved these changes

2024-02-15 09:13 UTC, merged